/*
 * Copyright (c) 2023-2025, NeKz
 *
 * SPDX-License-Identifier: MIT
 *
 * Migrates already rendered videos to S3 object storage:
 *   - Uploads every processed video in the videos folder to the bucket,
 *     updates video_url + video_external_id and deletes the local file.
 *     Videos with processed = 0 are skipped so that the processing task can
 *     generate thumbnails/previews from the local file first.
 *   - With --remote: also mirrors videos hosted on an external CDN (e.g. the
 *     old instance's Bunny CDN) into the bucket. Thumbnails and previews are
 *     regenerated by `deno task processing` which also cleans up the
 *     downloaded local file afterwards.
 *
 * Usage: deno task migrate (--dry-run) (--keep-local) (--remote)
 */

import { db } from '../db.ts';
import { Video } from '~/shared/models.ts';
import { S3Client } from '../s3.ts';
import { getVideoDownloadFilename, getVideoFilePath } from '../utils.ts';

const S3_ENABLED = Deno.env.get('S3_ENABLED')?.toLowerCase() === 'true';

if (!S3_ENABLED) {
  console.log('S3 is not enabled. Set S3_ENABLED=true and the other S3_* variables first.');
  Deno.exit(1);
}

const dryRun = Deno.args.includes('--dry-run');
const keepLocal = Deno.args.includes('--keep-local');
const includeRemote = Deno.args.includes('--remote');

const s3 = new S3Client({
  userAgent: Deno.env.get('USER_AGENT')!,
  endpoint: Deno.env.get('S3_ENDPOINT')!,
  region: Deno.env.get('S3_REGION')!,
  bucket: Deno.env.get('S3_BUCKET')!,
  accessKey: Deno.env.get('S3_ACCESS_KEY')!,
  secretKey: Deno.env.get('S3_SECRET_KEY')!,
});

// Everything under this prefix already lives in the bucket.
const bucketBaseUrl = s3.getObjectUrl('');

type VideoSelect = Pick<Video, 'video_id' | 'share_id' | 'title' | 'file_name' | 'video_url'>;

const selectColumns = `select BIN_TO_UUID(video_id) as video_id
        , share_id
        , title
        , file_name
        , video_url
     from videos`;

const localVideos = await db.query<VideoSelect>(
  `${selectColumns}
    where video_url like '%/storage/videos/%'
      and processed = 1
      and deleted_at is null`,
);

const remoteVideos = includeRemote
  ? await db.query<VideoSelect>(
    `${selectColumns}
      where video_url is not null
        and video_url not like '%/storage/videos/%'
        and video_url not like concat(?, '%')
        and deleted_at is null`,
    [bucketBaseUrl],
  )
  : [];

const videos = [
  ...localVideos.map((video) => ({ video, remote: false })),
  ...remoteVideos.map((video) => ({ video, remote: true })),
];

console.log(
  `Found ${localVideos.length} local and ${remoteVideos.length} remote videos to migrate${dryRun ? ' (dry run)' : ''}`,
);

let migrated = 0;
let skipped = 0;
let failed = 0;
let uploadedBytes = 0;

for (const [index, { video, remote }] of videos.entries()) {
  const progress = `[${index + 1}/${videos.length}]`;
  const filePath = getVideoFilePath(video);
  const fileName = `${video.share_id}.mp4`;

  try {
    if (remote) {
      if (dryRun) {
        console.log(`${progress} ${video.share_id} : would mirror ${video.video_url}`);
        migrated += 1;
        continue;
      }

      const res = await fetch(video.video_url, {
        headers: { 'User-Agent': Deno.env.get('USER_AGENT')! },
      });

      if (!res.ok || !res.body) {
        await res.body?.cancel();
        console.log(`${progress} ${video.share_id} : download returned ${res.status}, skipped`);
        skipped += 1;
        continue;
      }

      {
        using file = await Deno.open(filePath, { create: true, write: true, truncate: true });
        await res.body.pipeTo(file.writable);
      }
    } else {
      const stat = await Deno.stat(filePath).catch(() => null);
      if (!stat) {
        console.log(`${progress} ${video.share_id} : missing local file, skipped`);
        skipped += 1;
        continue;
      }

      if (dryRun) {
        console.log(`${progress} ${video.share_id} : would upload ${stat.size} bytes`);
        migrated += 1;
        continue;
      }
    }

    const fileContents = await Deno.readFile(filePath);

    await s3.putObject({
      key: fileName,
      contents: fileContents,
      contentType: 'video/mp4',
      contentDisposition: `attachment; filename="${encodeURIComponent(getVideoDownloadFilename(video))}"`,
    });

    const videoUrl = s3.getObjectUrl(fileName);

    if (remote) {
      // Reset the thumbnails/previews which point at the external CDN. The
      // processing task regenerates them from the local file and deletes it
      // afterwards since video_external_id is set.
      await db.execute(
        `update videos
            set video_url = ?
              , video_external_id = ?
              , video_size = ?
              , video_preview_url = null
              , thumbnail_url_large = null
              , thumbnail_url_small = null
              , processed = 0
          where video_id = UUID_TO_BIN(?)`,
        [
          videoUrl,
          fileName,
          fileContents.byteLength,
          video.video_id,
        ],
      );
    } else {
      await db.execute(
        `update videos
            set video_url = ?
              , video_external_id = ?
          where video_id = UUID_TO_BIN(?)`,
        [
          videoUrl,
          fileName,
          video.video_id,
        ],
      );

      if (!keepLocal) {
        try {
          await Deno.remove(filePath);
        } catch (err) {
          console.log(`${progress} ${video.share_id} : failed to remove local file :`, err);
        }
      }
    }

    migrated += 1;
    uploadedBytes += fileContents.byteLength;

    console.log(`${progress} ${video.share_id} : ${videoUrl}`);
  } catch (err) {
    failed += 1;
    console.log(`${progress} ${video.share_id} : failed :`, err);
  }
}

console.log(
  `Done. ${dryRun ? 'Would migrate' : 'Migrated'} ${migrated}, skipped ${skipped}, failed ${failed}` +
    (dryRun ? '' : ` (${Math.round(uploadedBytes / 1e6)} MB uploaded)`),
);

if (!dryRun && remoteVideos.length) {
  console.log('Run or wait for `deno task processing` to regenerate thumbnails/previews of mirrored videos.');
}

Deno.exit(failed ? 1 : 0);
